# Generated by Django 2.1.1 on 2018-09-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц загрузки')),
                ('load', models.FloatField(verbose_name='Коэффициент загрузки')),
                ('state', models.CharField(choices=[('DR', 'Черновик'), ('PL', 'Планируемое участие'), ('FA', 'Фактическое участие')], default='DR', max_length=2, verbose_name='Статус данных о загрузке')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('fire_date', models.DateField(blank=True, default=None, verbose_name='Дата увольнения')),
                ('is_fulltime', models.BooleanField(default=True, verbose_name='Работает полный день?')),
                ('business_k', models.FloatField(default=0.5, verbose_name='Коэффициент участия в бизнесе')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('short_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Сокращенное название проекта')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное название проекта')),
                ('business', models.CharField(max_length=20, verbose_name='Бизнес')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('finish_date', models.DateField(blank=True, default=None, verbose_name='Дата окончания проекта')),
                ('budget_state', models.CharField(choices=[('NO', 'Не создан'), ('PR', 'Проект согласуется'), ('AP', 'Утвержден')], default='NO', max_length=2, verbose_name='Статус бюджета')),
                ('head', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pplan.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Оклад')),
                ('start_date', models.DateField(verbose_name='Дата изменения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Project'),
        ),
    ]
