# Generated by Django 2.1.1 on 2018-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='is_lead',
        ),
        migrations.AddField(
            model_name='role',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Руководитель проекта?'),
        ),
    ]
