# Generated by Django 2.1.1 on 2018-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата увольнения'),
        ),
    ]
