# Generated by Django 2.1.1 on 2018-10-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'verbose_name': 'загрузка по месяцам', 'verbose_name_plural': 'статистика загрузки по месяцам'},
        ),
    ]
