# Generated by Django 2.1.1 on 2018-11-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0002_auto_20181010_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBookingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'загрузка по месяцам',
                'verbose_name_plural': 'отчет о загрузке по месяцам',
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.monthbooking',),
        ),
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'verbose_name': 'плановая загрузка за месяц', 'verbose_name_plural': 'данные плановой загрузки по месяцам'},
        ),
        migrations.AlterModelOptions(
            name='projectbooking',
            options={'verbose_name': 'загрузка по проектам', 'verbose_name_plural': 'отчет о загрузке по проектам'},
        ),
    ]
