# Generated by Django 2.1.1 on 2018-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0002_auto_20180914_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(verbose_name='Оклад'),
        ),
    ]
