# Generated by Django 2.1.1 on 2018-11-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0003_auto_20181101_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBookingEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'загрузка по сотруднику',
                'verbose_name_plural': 'отчет о загрузке по сотруднику',
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.monthbooking',),
        ),
    ]
