# Generated by Django 2.1.1 on 2018-09-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0003_auto_20180918_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('project_member', 'month'), 'verbose_name': 'загрузка участника', 'verbose_name_plural': 'загрузка участников'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('project', 'employee'), 'verbose_name': 'участник проекта', 'verbose_name_plural': 'участники проекта'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_fulltime',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_3d',
            field=models.BooleanField(default=False, verbose_name='Участник 3D?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='load',
            field=models.FloatField(default=100, verbose_name='Процент загрузки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.ProjectMember', verbose_name='Участник проекта'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Employee', verbose_name='Сотрудник'),
        ),
    ]
