# Generated by Django 2.1.1 on 2018-09-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0003_auto_20180914_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(unique_for_date='start_date', verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Employee', verbose_name='Сотрудник'),
        ),
    ]
