# Generated by Django 2.1.1 on 2018-09-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0004_auto_20180915_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'get_latest_by': 'start_date', 'ordering': ('start_date', 'employee'), 'verbose_name': 'оклад', 'verbose_name_plural': 'оклады'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(verbose_name='Оклад'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'start_date')},
        ),
    ]
