# Generated by Django 2.1.1 on 2018-09-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0004_auto_20180918_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('lead', models.CharField(max_length=200, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'бизнес',
                'verbose_name_plural': 'бизнесы',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_3d',
            field=models.BooleanField(default=False, verbose_name='Участник системы 3D ?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Business', verbose_name='Бизнес'),
        ),
    ]
