# Generated by Django 2.1.1 on 2018-11-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pplan', '0004_monthbookingemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBookingSelf',
            fields=[
                ('monthbooking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pplan.MonthBooking')),
            ],
            bases=('pplan.monthbookingemployee',),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
