# Generated by Django 2.1.1 on 2018-09-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0005_auto_20180915_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': 'start_date', 'ordering': ('start_date', 'short_name'), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('IN', 'Проект планируется'), ('OP', 'Проект открыт'), ('CL', 'Проект в стадии закрытия'), ('CD', 'Проект закрыт')], default='IN', max_length=2, verbose_name='Статус проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_state',
            field=models.CharField(choices=[('NO', 'Бюджет не создан'), ('PR', 'Бюджет согласуется'), ('AP', 'Бюджет утвержден')], default='NO', max_length=2, verbose_name='Состояние бюджета'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, default=None, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='head',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pplan.Employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
