# Generated by Django 2.1.1 on 2018-09-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0006_auto_20180919_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate', to='pplan.Employee', verbose_name='Руководитель'),
        ),
    ]
