# Generated by Django 2.1.1 on 2018-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0006_auto_20180915_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_state',
            field=models.CharField(choices=[('NO', 'Бюджет планируется'), ('PR', 'Бюджет согласуется'), ('AP', 'Бюджет утвержден')], default='NO', max_length=2, verbose_name='Состояние бюджета'),
        ),
    ]
