# Generated by Django 2.1.1 on 2018-11-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0007_monthbookingself'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthbooking',
            unique_together={('booking', 'month')},
        ),
    ]
