# Generated by Django 2.1.1 on 2018-11-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0008_auto_20181122_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbookingemployee',
            options={'permissions': (('view_all', 'Просмотр любого сотрудника'),), 'verbose_name': 'загрузка по сотруднику', 'verbose_name_plural': 'отчет о загрузке по сотруднику'},
        ),
        migrations.AlterField(
            model_name='division',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed', to='pplan.Employee', verbose_name='Руководитель'),
        ),
    ]
