# Generated by Django 2.1.1 on 2018-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0008_auto_20180919_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',), 'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
    ]
