# Generated by Django 2.1.1 on 2018-09-20 13:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0009_auto_20180919_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ('division', 'position_name'),
            },
        ),
        migrations.CreateModel(
            name='PositionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'наименование должности',
                'verbose_name_plural': 'наименования должностей',
            },
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='local_phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон мобильный'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон корпоративный'),
        ),
        migrations.AddField(
            model_name='position',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Division', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='position',
            name='position_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pplan.PositionName', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pplan.Position', verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('position_name', 'division')},
        ),
    ]
