# Generated by Django 2.1.1 on 2018-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0010_auto_20180920_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionname',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование должности'),
        ),
    ]
