# Generated by Django 2.1.1 on 2018-11-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0010_auto_20181127_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbookingemployee',
            options={'permissions': (('view_all', 'Просмотр любого сотрудника'),), 'verbose_name': 'загрузка по сотруднику', 'verbose_name_plural': 'отчет о загрузке по сотруднику'},
        ),
    ]
