# Generated by Django 2.1.1 on 2018-09-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0011_auto_20180921_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',), 'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.AlterModelOptions(
            name='positionname',
            options={'ordering': ('name',), 'verbose_name': 'наименование должности', 'verbose_name_plural': 'наименования должностей'},
        ),
    ]
