# Generated by Django 2.1.3 on 2018-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0011_auto_20181127_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthBookingEmployee',
        ),
        migrations.DeleteModel(
            name='MonthBookingSummary',
        ),
        migrations.DeleteModel(
            name='ProjectBooking',
        ),
    ]
