# Generated by Django 2.1.3 on 2018-12-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0012_auto_20181215_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'default_permissions': ('view',), 'verbose_name': 'плановая загрузка за месяц', 'verbose_name_plural': 'данные плановой загрузки по месяцам'},
        ),
    ]
