# Generated by Django 2.1.1 on 2018-09-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0013_auto_20180921_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('project_member', 'month'), 'verbose_name': 'данные загрузки', 'verbose_name_plural': 'данные загрузки'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('project', '-role__is_lead', 'employee'), 'verbose_name': 'участник проекта', 'verbose_name_plural': 'участники проектов'},
        ),
    ]
