# Generated by Django 2.1.3 on 2018-12-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0013_auto_20181215_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('project_member', 'start_date'), 'verbose_name': 'загрузка в проекте', 'verbose_name_plural': 'загрузка в проекте'},
        ),
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'default_permissions': ('view',), 'verbose_name': 'загрузка за месяц', 'verbose_name_plural': 'загрузки по месяцам'},
        ),
    ]
