# Generated by Django 2.1.3 on 2018-12-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0014_auto_20181215_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'default_permissions': (), 'verbose_name': 'загрузка за месяц', 'verbose_name_plural': 'загрузки по месяцам'},
        ),
    ]
