# Generated by Django 2.1.1 on 2018-09-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0014_auto_20180924_1643'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='StaffingTable',
        ),
        migrations.AlterModelOptions(
            name='staffingtable',
            options={'ordering': ('division', 'position'), 'verbose_name': 'должность', 'verbose_name_plural': 'должности'},
        ),
        migrations.RenameField(
            model_name='staffingtable',
            old_name='position_name',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='staffingtable',
            unique_together={('position', 'division')},
        ),
    ]
