# Generated by Django 2.1.1 on 2018-09-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0015_auto_20180924_1655'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='PositionName',
            new_name='Position',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',), 'verbose_name': 'должности', 'verbose_name_plural': 'должности'},
        ),
        migrations.AlterModelOptions(
            name='staffingtable',
            options={'ordering': ('division', 'position'), 'verbose_name': 'должность по штатному расписанию', 'verbose_name_plural': 'должности по штатному расписанию'},
        ),
    ]
