# Generated by Django 2.1.3 on 2018-12-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0015_auto_20181216_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffingtable',
            options={'ordering': ('division', 'position'), 'verbose_name': 'позиция штатного расписания', 'verbose_name_plural': 'позиции штатного расписания'},
        ),
    ]
