# Generated by Django 2.1.1 on 2018-09-25 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0020_staffingtable_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='staffingtable',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Число позиций'),
        ),
    ]
