# Generated by Django 2.1.1 on 2018-09-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0021_auto_20180925_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pplan.Position', verbose_name='Занимаемая должность'),
        ),
    ]
