# Generated by Django 2.1.1 on 2018-09-26 08:10

import django.core.validators
from django.db import migrations, models
import pplan.models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0022_auto_20180925_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('project_member', 'start_date'), 'verbose_name': 'данные загрузки', 'verbose_name_plural': 'данные загрузки'},
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='start_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='finish_date',
            field=models.DateField(default=pplan.models.tomorrow, verbose_name='Окончание загрузки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=pplan.models.today, verbose_name='Начало загрузки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_k',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Коэффициент участия в бизнесе'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Оклад'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('project_member', 'start_date', 'state')},
        ),
    ]
