# Generated by Django 2.1.1 on 2018-09-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0023_auto_20180926_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
    ]
