# Generated by Django 2.1.1 on 2018-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0024_remove_booking_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('DR', 'Черновик'), ('PL', 'Планируемое участие'), ('FA', 'Фактическое участие')], default='PL', max_length=2, verbose_name='Статус данных о загрузке'),
        ),
    ]
