# Generated by Django 2.1.1 on 2018-09-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0025_auto_20180926_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
