# Generated by Django 2.1.1 on 2018-09-27 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0026_auto_20180926_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('RF', 'Российский паспорт'), ('IN', 'Заграничный паспорт')], default='RF', max_length=2, verbose_name='Тип документа')),
                ('series', models.CharField(max_length=20, verbose_name='Серия')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('issuer', models.DateField(verbose_name='Кем выдан')),
                ('registered', models.TextField(verbose_name='Зарегистрирован')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pplan.Employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'паспортные данные',
                'verbose_name_plural': 'паспортные данные',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='load',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент загрузки'),
        ),
    ]
