# Generated by Django 2.1.1 on 2018-09-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0027_auto_20180927_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ('-is_valid', 'issue_date'), 'verbose_name': 'паспортные данные', 'verbose_name_plural': 'паспортные данные'},
        ),
        migrations.AddField(
            model_name='passport',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Действителен'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registered',
            field=models.CharField(max_length=200, verbose_name='Зарегистрирован'),
        ),
    ]
