# Generated by Django 2.1.1 on 2018-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0028_auto_20180927_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='issuer',
            field=models.CharField(max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registered',
            field=models.TextField(verbose_name='Зарегистрирован'),
        ),
    ]
