# Generated by Django 2.1.1 on 2018-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0029_auto_20180927_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ('-is_valid', 'issue_date'), 'verbose_name': 'паспорт', 'verbose_name_plural': 'паспортные данные'},
        ),
        migrations.AlterField(
            model_name='passport',
            name='registered',
            field=models.TextField(blank=True, null=True, verbose_name='Зарегистрирован'),
        ),
    ]
