# Generated by Django 2.1.1 on 2018-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0031_monthbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBooking',
            fields=[
            ],
            options={
                'verbose_name': 'статистика загрузки сотрудника',
                'verbose_name_plural': 'статистика загрузки сотрудников',
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.employee',),
        ),
        migrations.AlterField(
            model_name='monthbooking',
            name='load',
            field=models.FloatField(default=0, verbose_name='Загрузка, %'),
        ),
    ]
