# Generated by Django 2.1.1 on 2018-10-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplan', '0032_auto_20181003_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeBooking',
        ),
        migrations.AlterModelOptions(
            name='monthbooking',
            options={'verbose_name': 'месячная загрузка', 'verbose_name_plural': 'статистика месячной загрузки'},
        ),
        migrations.AlterField(
            model_name='monthbooking',
            name='month',
            field=models.DateField(db_index=True, verbose_name='Месяц'),
        ),
    ]
