# Generated by Django 2.1.4 on 2018-12-18 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'наименование праздника',
                'verbose_name_plural': 'наименования праздников',
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('daytype', models.CharField(choices=[('HL', 'Нерабочий день'), ('SH', 'Сокращенный день'), ('WK', 'Рабочий день')], default='HL', max_length=2, verbose_name='Тип дня')),
                ('shorthours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Сокращение дня, час')),
                ('dayname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workdays.HolidayName', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'особый календарный день',
                'verbose_name_plural': 'особые календарные дни',
            },
        ),
    ]
