# Generated by Django 2.1.4 on 2018-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialday',
            name='shorthours',
        ),
        migrations.AlterField(
            model_name='holidayname',
            name='dayname',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='daytype',
            field=models.CharField(choices=[('HL', 'Выходной день'), ('SH', 'Сокращенный день'), ('WK', 'Рабочий день')], default='HL', max_length=2, verbose_name='Тип дня'),
        ),
    ]
