# Generated by Django 2.1.4 on 2018-12-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0002_auto_20181219_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ('date',), 'verbose_name': 'специальный день', 'verbose_name_plural': 'специальные календарные дни'},
        ),
        migrations.AlterField(
            model_name='holidayname',
            name='dayname',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='dayname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workdays.HolidayName', verbose_name='Название'),
        ),
    ]
