# Generated by Django 2.1.4 on 2018-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0003_auto_20181219_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorktimeStandards',
            fields=[
            ],
            options={
                'verbose_name': 'норма рабочего времени',
                'verbose_name_plural': 'нормы рабочего времени',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
            },
            bases=('workdays.specialday',),
        ),
        migrations.AlterModelOptions(
            name='holidayname',
            options={'ordering': ('ordering',), 'verbose_name': 'наименование праздника', 'verbose_name_plural': 'наименования праздников'},
        ),
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ('date',), 'verbose_name': 'праздничный и перенесенный день', 'verbose_name_plural': 'праздничные и перенесенные дни'},
        ),
        migrations.AddField(
            model_name='holidayname',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidayname',
            name='dayname',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
