# Generated by Django 2.1.4 on 2018-12-20 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0004_auto_20181220_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayname',
            options={'ordering': ('month', 'day'), 'verbose_name': 'наименование праздника', 'verbose_name_plural': 'наименования праздников'},
        ),
        migrations.RemoveField(
            model_name='holidayname',
            name='ordering',
        ),
        migrations.AddField(
            model_name='holidayname',
            name='day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День'),
        ),
        migrations.AddField(
            model_name='holidayname',
            name='days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Число дней'),
        ),
        migrations.AddField(
            model_name='holidayname',
            name='month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц'),
        ),
    ]
