# Generated by Django 2.1.4 on 2018-12-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0005_auto_20181220_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayname',
            old_name='days',
            new_name='count',
        ),
    ]
