# Generated by Django 2.1.4 on 2018-12-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0006_auto_20181220_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ('date',), 'verbose_name': 'день производственного календаря', 'verbose_name_plural': 'дни производственного календаря'},
        ),
    ]
