# Generated by Django 2.1.4 on 2018-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0007_auto_20181220_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ('date',), 'verbose_name': 'измененный день календаря', 'verbose_name_plural': 'измененные дни календаря'},
        ),
        migrations.AddField(
            model_name='specialday',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
