# Generated by Django 2.1.4 on 2018-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0008_auto_20181224_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
