# Generated by Django 2.1.4 on 2018-12-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0009_auto_20181224_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ('date',), 'verbose_name': 'нестандартный день календаря', 'verbose_name_plural': 'нестандартные дни календаря'},
        ),
    ]
