# Generated by Django 2.1.3 on 2018-12-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pplan', '0012_auto_20181215_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBookingEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'загрузка по сотруднику',
                'verbose_name_plural': 'отчет о загрузке по сотруднику',
                'permissions': (('view_all', 'Просмотр любого сотрудника'),),
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.monthbooking',),
        ),
        migrations.CreateModel(
            name='MonthBookingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'загрузка по месяцам',
                'verbose_name_plural': 'отчет о загрузке по месяцам',
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.monthbooking',),
        ),
        migrations.CreateModel(
            name='ProjectBooking',
            fields=[
            ],
            options={
                'verbose_name': 'загрузка по проектам',
                'verbose_name_plural': 'отчет о загрузке по проектам',
                'proxy': True,
                'indexes': [],
            },
            bases=('pplan.monthbooking',),
        ),
    ]
