# Generated by Django 2.1.3 on 2018-12-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbookingemployee',
            options={'default_permissions': ('view',), 'permissions': (('view_all', 'Просмотр любого сотрудника'),), 'verbose_name': 'загрузка по сотруднику', 'verbose_name_plural': 'отчет о загрузке по сотруднику'},
        ),
        migrations.AlterModelOptions(
            name='monthbookingsummary',
            options={'default_permissions': ('view',), 'verbose_name': 'загрузка по месяцам', 'verbose_name_plural': 'отчет о загрузке по месяцам'},
        ),
        migrations.AlterModelOptions(
            name='projectbooking',
            options={'default_permissions': ('view',), 'verbose_name': 'загрузка по проектам', 'verbose_name_plural': 'отчет о загрузке по проектам'},
        ),
    ]
