# Generated by Django 2.1.3 on 2018-12-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pstat', '0002_auto_20181215_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthbookingemployee',
            options={'default_permissions': ('view',), 'permissions': (('view_all', 'Просмотр любого сотрудника'),), 'verbose_name': 'отчет о загрузке по сотруднику', 'verbose_name_plural': 'отчет о загрузке по сотруднику'},
        ),
        migrations.AlterModelOptions(
            name='monthbookingsummary',
            options={'default_permissions': ('view',), 'verbose_name': 'сводный отчет о загрузке по месяцам', 'verbose_name_plural': 'сводный отчет о загрузке по месяцам'},
        ),
        migrations.AlterModelOptions(
            name='projectbooking',
            options={'default_permissions': ('view',), 'verbose_name': 'отчет о загрузке по проектам', 'verbose_name_plural': 'отчет о загрузке по проектам'},
        ),
    ]
