# Generated by Django 2.1.3 on 2019-01-06 16:06

from django.db import migrations, models
import jiradata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customfield',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('customfieldtypekey', models.CharField(max_length=255, verbose_name='Ключ типа поля')),
                ('customfieldsearcherkey', models.CharField(max_length=255, verbose_name='Ключ поиска')),
                ('cfname', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('description', models.TextField(verbose_name='Описание поля')),
                ('defaultvalue', models.CharField(max_length=255, verbose_name='Значение по умолчанию')),
                ('fieldtype', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Тип поля')),
                ('project', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Проект')),
                ('issuetype', models.CharField(max_length=255, verbose_name='Тип запроса')),
            ],
            options={
                'verbose_name': 'определение пользовательского поля',
                'verbose_name_plural': 'определения пользовательских полей',
                'db_table': 'customfield',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='CustomfieldOption',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('customfield', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Пользовательское поле')),
                ('sequence', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Последовательный номер')),
                ('customvalue', models.CharField(max_length=255, verbose_name='Значение')),
                ('optiontype', models.CharField(max_length=60, verbose_name='Тип значения')),
                ('disabled', models.CharField(max_length=60, verbose_name='Не активно')),
            ],
            options={
                'verbose_name': 'опция пользовательского поля',
                'verbose_name_plural': 'опции пользовательских полей',
                'db_table': 'customfieldoption',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='CustomfieldValue',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Запрос')),
                ('customfield', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Пользовательское поле')),
                ('parentkey', models.CharField(max_length=255, verbose_name='Родительской ключ')),
                ('stringvalue', models.CharField(max_length=255, verbose_name='Строковое значение')),
                ('numbervalue', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Числовое значение')),
                ('textvalue', models.TextField(verbose_name='Текстовое значение')),
                ('datevalue', models.DateTimeField(verbose_name='Значение даты и времени')),
                ('valuetype', models.CharField(max_length=255, verbose_name='Тип значения')),
            ],
            options={
                'verbose_name': 'значение пользовательского поля',
                'verbose_name_plural': 'значения пользовательских полей',
                'db_table': 'customfieldvalue',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuenum', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Номер')),
                ('project', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Проект')),
                ('reporter', models.CharField(max_length=255, verbose_name='Заявитель')),
                ('assignee', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('summary', models.CharField(max_length=255, verbose_name='Запрос')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('priority', models.CharField(max_length=255, verbose_name='Приоритет')),
                ('resolution', models.CharField(max_length=255, verbose_name='Резолюция')),
                ('issuestatus', models.CharField(max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата изменения')),
                ('duedate', models.DateTimeField(verbose_name='Дата завершения')),
                ('resolutiondate', models.DateTimeField(verbose_name='Дата резолюции')),
                ('timespent', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Затраченное время, c')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': 'запросы',
                'db_table': 'jiraissue',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
            bases=(models.Model, jiradata.models.BudgetCustomField),
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_id', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='ID')),
                ('user_name', models.CharField(db_column='lower_user_name', max_length=255, verbose_name='Пользователь')),
                ('active', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Проект')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(verbose_name='Дата изменения')),
                ('first_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email_address', models.CharField(db_column='lower_email_address', max_length=255, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'cwd_user',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Создал')),
                ('worklogbody', models.TextField(verbose_name='Содержание работ')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updateauthor', models.CharField(max_length=255, verbose_name='Изменил')),
                ('updated', models.DateTimeField(verbose_name='Дата изменения')),
                ('startdate', models.DateTimeField(verbose_name='Дата выполнения работ')),
                ('timeworked', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Затраченное время, c')),
            ],
            options={
                'verbose_name': 'запись о работе',
                'verbose_name_plural': 'записи о выполнении работ',
                'db_table': 'worklog',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
            bases=(models.Model, jiradata.models.BudgetCustomField),
        ),
        migrations.CreateModel(
            name='WorklogIssues',
            fields=[
            ],
            options={
                'verbose_name': 'затраты времени по задаче',
                'verbose_name_plural': 'отчет о затратах времени по задачам',
                'permissions': (('view_all', 'Просмотр любого сотрудника'),),
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
            },
            bases=('jiradata.worklog',),
        ),
        migrations.CreateModel(
            name='WorklogReport',
            fields=[
            ],
            options={
                'verbose_name': 'фактическая загрузка по сотруднику',
                'verbose_name_plural': 'отчет о фактической загрузке по сотруднику',
                'permissions': (('view_all', 'Просмотр любого сотрудника'),),
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
            },
            bases=('jiradata.worklog',),
        ),
        migrations.CreateModel(
            name='WorklogSummary',
            fields=[
            ],
            options={
                'verbose_name': 'фактическая загрузка по месяцам',
                'verbose_name_plural': 'сводный отчет о фактической загрузке',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
            },
            bases=('jiradata.worklog',),
        ),
    ]
