# Generated by Django 2.1.3 on 2019-01-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX idx_worklog_author ON worklog (author)"),
        migrations.RunSQL("CREATE INDEX idx_worklog_created ON worklog (created)"),
    ]
