# Generated by Django 2.1.5 on 2019-01-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklogsummary',
            options={'default_permissions': ('view',), 'permissions': (('view_all', 'Просмотр любого бюджета'),), 'verbose_name': 'фактическая загрузка по месяцам', 'verbose_name_plural': 'отчет о фактической загрузке по месяцам'},
        ),
    ]
