# Generated by Django 2.1.4 on 2018-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customfield',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('customfieldtypekey', models.CharField(max_length=255, verbose_name='Ключ типа поля')),
                ('customfieldsearcherkey', models.CharField(max_length=255, verbose_name='Ключ поиска')),
                ('cfname', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('description', models.TextField(verbose_name='Описание поля')),
                ('defaultvalue', models.CharField(max_length=255, verbose_name='Значение по умолчанию')),
                ('fieldtype', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Тип поля')),
                ('project', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Проект')),
                ('issuetype', models.CharField(max_length=255, verbose_name='Тип запроса')),
            ],
            options={
                'verbose_name': 'определение пользовательского поля',
                'verbose_name_plural': 'определения пользовательских полей',
                'db_table': 'customfield',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomfieldValue',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Запрос')),
                ('customfield', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Пользовательское поле')),
                ('parentkey', models.CharField(max_length=255, verbose_name='Родительской ключ')),
                ('stringvalue', models.CharField(max_length=255, verbose_name='Строковое значение')),
                ('numbervalue', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Числовое значение')),
                ('textvalue', models.TextField(verbose_name='Текстовое значение')),
                ('datevalue', models.DateTimeField(verbose_name='Значение даты и времени')),
                ('valuetype', models.CharField(max_length=255, verbose_name='Тип значения')),
            ],
            options={
                'verbose_name': 'значение пользовательского поля',
                'verbose_name_plural': 'значения пользовательских полей',
                'db_table': 'customfieldvalue',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
