# Generated by Django 2.1.4 on 2018-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0002_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuenum', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Номер запроса')),
                ('project', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Проект')),
                ('reporter', models.CharField(max_length=255, verbose_name='Заявитель')),
                ('assignee', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('summary', models.CharField(max_length=255, verbose_name='Запрос')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('priority', models.CharField(max_length=255, verbose_name='Приоритет')),
                ('resolution', models.CharField(max_length=255, verbose_name='Резолюция')),
                ('issuestatus', models.CharField(max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата изменения')),
                ('duedate', models.DateTimeField(verbose_name='Дата завершения')),
                ('resolutiondate', models.DateTimeField(verbose_name='Дата резолюции')),
                ('timespent', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Затраченное время, c')),
            ],
            options={
                'verbose_name': 'запрос Jira',
                'verbose_name_plural': 'запросы Jira',
                'db_table': 'jiraissue',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
